### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by kmcquade** [reetasingh/terraform-provider-policy-sentry#9] opened 2020-11-14 21:37 UTC
We should add unit tests. I noticed that make test is in the Makefile but we need Golang tests.

Probably less important in the short term than some of these other items but will be good for long term maintenance.

**Comment by sahilvv** [comment] 2020-11-15 18:00
Duplicate of issue #1

**Closed as completed by sahilvv** 2020-11-15 18:00 UTC
